export const MAIN_SCRIPT_INJECTED = 'MAIN_SCRIPT_INJECTED'
export const LOGGED_OUT_OF_POCKET = 'LOGGED_OUT_OF_POCKET'
export const ARCHIVE_ITEM = 'ARCHIVE_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const OPEN_POCKET = 'OPEN_POCKET'
export const AUTH_CODE_RECEIVED = 'AUTH_CODE_RECEIVED'
export const COLOR_MODE_CHANGE = 'COLOR_MODE_CHANGE'

export const SAVE_TO_POCKET_REQUEST = 'SAVE_TO_POCKET_REQUEST'
export const SAVE_TO_POCKET_SUCCESS = 'SAVE_TO_POCKET_SUCCESS'
export const SAVE_TO_POCKET_FAILURE = 'SAVE_TO_POCKET_FAILURE'
export const SAVE_TO_POCKET_UPDATE = 'SAVE_TO_POCKET_UPDATE'
export const SAVE_TO_POCKET_COMPLETE = 'SAVE_TO_POCKET_COMPLETE'

export const ARCHIVE_ITEM_REQUEST = 'ARCHIVE_ITEM_REQUEST'
export const ARCHIVE_ITEM_SUCCESS = 'ARCHIVE_ITEM_SUCCESS'
export const ARCHIVE_ITEM_FAILURE = 'ARCHIVE_ITEM_FAILURE'

export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE'

export const SUGGESTED_TAGS_REQUEST = 'SUGGESTED_TAGS_REQUEST'
export const SUGGESTED_TAGS_SUCCESS = 'SUGGESTED_TAGS_SUCCESS'
export const SUGGESTED_TAGS_FAILURE = 'SUGGESTED_TAGS_FAILURE'

export const TAG_ACTIVATE = 'TAG_ACTIVATE'
export const TAG_DEACTIVATE = 'TAG_DEACTIVATE'
export const TAGS_DEACTIVATE = 'TAGS_DEACTIVATE'
export const TAG_ADD = 'TAG_ADD'
export const TAG_REMOVE = 'TAG_REMOVE'
export const TAGS_REMOVE = 'TAGS_REMOVE'
export const TAGS_ADDED_FAILURE = 'TAGS_ADDED_FAILURE'
export const TAGS_ADDED_SUCCESS = 'TAGS_ADDED_SUCCESS'

export const EDIT_TAGS = 'EDIT_TAGS'
export const TAGS_SYNC = 'TAGS_SYNC'
export const TAG_SYNC_REQUEST = 'TAG_SYNC_REQUEST'
export const TAG_SYNC_SUCCESS = 'TAG_SYNC_SUCCESS'
export const TAG_SYNC_FAILURE = 'TAG_SYNC_FAILURE'

export const UPDATE_STORED_TAGS = 'UPDATE_STORED_TAGS'

export const USER_LOG_IN = 'USER_LOG_IN'
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS'
export const USER_LOG_IN_FAILURE = 'USER_LOG_IN_FAILURE'

export const USER_LOG_OUT = 'USER_LOG_OUT'
export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS'
export const USER_LOG_OUT_FAILURE = 'USER_LOG_IN_FAILURE'

export const GET_RECS_REQUEST = 'GET_RECS_REQUEST'
export const GET_RECS_SUCCESS = 'GET_RECS_SUCCESS'
export const GET_RECS_FAILURE = 'GET_RECS_FAILURE'

export const SAVE_REC_REQUEST = 'SAVE_REC_REQUEST'
export const SAVE_REC_SUCCESS = 'SAVE_REC_SUCCESS'
export const SAVE_REC_FAILURE = 'SAVE_REC_FAILURE'

export const OPEN_REC = 'OPEN_REC'
