export const LOGGED_OUT_OF_POCKET = 'LOGGED_OUT_OF_POCKET'
export const OPEN_POCKET = 'OPEN_POCKET'
export const AUTH_CODE_RECEIVED = 'AUTH_CODE_RECEIVED'
export const COLOR_MODE_CHANGE = 'COLOR_MODE_CHANGE'
export const OPEN_OPTIONS = 'OPEN_OPTIONS'

export const SAVE_TO_POCKET_REQUEST = 'SAVE_TO_POCKET_REQUEST'
export const SAVE_TO_POCKET_SUCCESS = 'SAVE_TO_POCKET_SUCCESS'
export const SAVE_TO_POCKET_FAILURE = 'SAVE_TO_POCKET_FAILURE'

export const RESAVE_ITEM = 'RESAVE_ITEM'

export const UPDATE_ITEM_PREVIEW = 'UPDATE_ITEM_PREVIEW'

export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE'

export const SUGGESTED_TAGS_SUCCESS = 'SUGGESTED_TAGS_SUCCESS'
export const SUGGESTED_TAGS_FAILURE = 'SUGGESTED_TAGS_FAILURE'

export const TAGS_SYNC = 'TAGS_SYNC'
export const TAG_SYNC_REQUEST = 'TAG_SYNC_REQUEST'
export const TAG_SYNC_SUCCESS = 'TAG_SYNC_SUCCESS'
export const TAG_SYNC_FAILURE = 'TAG_SYNC_FAILURE'

export const UPDATE_STORED_TAGS = 'UPDATE_STORED_TAGS'

export const SEND_TAG_ERROR = 'SEND_TAG_ERROR'
export const UPDATE_TAG_ERROR = 'UPDATE_TAG_ERROR'


export const USER_LOG_IN = 'USER_LOG_IN'
export const USER_LOG_OUT = 'USER_LOG_OUT'
