/* Dispatch messages to SAE
  –––––––––––––––––––––––––––––––––––––––––––––––––– */
export const MAIN_SCRIPT_INJECTED = 'MAIN_SCRIPT_INJECTED'
export const USER_LOG_OUT = 'USER_LOG_OUT'
export const ARCHIVE_ITEM = 'ARCHIVE_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const EDIT_TAGS = 'EDIT_TAGS'
export const OPEN_POCKET = 'OPEN_POCKET'

/* Dispatched messages from SAE
–––––––––––––––––––––––––––––––––––––––––––––––––– */

export const SAVE_TO_POCKET_REQUEST = 'SAVE_TO_POCKET_REQUEST'
export const SAVE_TO_POCKET_SUCCESS = 'SAVE_TO_POCKET_SUCCESS'
export const SAVE_TO_POCKET_FAILURE = 'SAVE_TO_POCKET_FAILURE'
export const SAVE_TO_POCKET_UPDATE = 'SAVE_TO_POCKET_UPDATE'

export const ARCHIVE_ITEM_REQUEST = 'ARCHIVE_ITEM_REQUEST'
export const ARCHIVE_ITEM_SUCCESS = 'ARCHIVE_ITEM_SUCCESS'
export const ARCHIVE_ITEM_FAILURE = 'ARCHIVE_ITEM_FAILURE'

export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_FAILURE'

export const TAGS_ADDED_SUCCESS = 'TAGS_ADDED_SUCCESS'
export const TAGS_ADDED_FAILURE = 'TAGS_ADDED_FAILURE'

export const SUGGESTED_TAGS_SUCCESS = 'SUGGESTED_TAGS_SUCCESS'
export const SUGGESTED_TAGS_FAILURE = 'SUGGESTED_TAGS_FAILURE'

export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS'
export const USER_LOG_IN_FAILURE = 'USER_LOG_IN_FAILURE'

export const USER_LOG_OUT_SUCCESS = 'USER_LOG_OUT_SUCCESS'
export const USER_LOG_OUT_FAILURE = 'USER_LOG_IN_FAILURE'
